### DISCUSSION TITLE
How do I pull this with docker compose?

### DISCUSSION THREAD

**Discussion by GD-Dal** [petrvlcek/bisecur2mqtt#2] [Q&A] [answered]
I have tried:

```
version: '3'
services:
  bisecur2mqtt:
    container_name: bisecur2mqtt
    build: https://github.com/petrvlcek/bisecur2mqtt.git
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env
```
But it does not work. Errors I'm seeing is:

```
Deployment error
failed to deploy a stack: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: failed to load cache key: repository does not contain ref master, output: "" 
```
Any help is appreciated
